filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/httpd/error_log
    - /var/log/httpd/access_log
output.elasticsearch:
  hosts: ["172.31.14.33:9200"]
  enabled: true
  index: "stgapache-%{[agent.version]}-%{+yyyy.MM}"
setup.kibana:
  host: "http://172.31.14.33:5601"
setup.dashboards.enabled: true
setup.dashboards.index: "stgapache-*"
setup.template.enabled: true
setup.template.name: "stgapache"
setup.template.pattern: "stgapache-*"
setup.template.overwrite: true
setup.template.settings:
  index:
    number_of_shards: 1
setup.ilm.enabled: false
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
