filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /opt/tomcat9/logs/catalina.2021-03-20.log
output.elasticsearch:
  hosts: ["172.31.14.20:9200"]
  enabled: true
  index: "stgtomcat-%{[agent.version]}-%{+yyyy.MM}"
setup.kibana:
  host: "http://172.31.14.20:5601"
setup.dashboards.enabled: true
setup.dashboards.index: "stgtomcat-*"
setup.template.enabled: true
setup.template.name: "stgtomcat"
setup.template.pattern: "stgtomcat-*"
setup.template.overwrite: true
setup.template.settings:
  index:
    number_of_shards: 1
setup.ilm.enabled: false
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
